### PR TITLE
Change the sidebar to have a table of contents for the page instead of a list of all the pages in the site

### PR DESCRIPTION
**Pull request by hackartisan**
- Upgrade to jekyll 4
- Overrides some includes to have a page-level TOC in the sidebar

I think this makes the page easier to parse and the sidebar helpful rather than overwhelming.

Side effect is that you have to go back to the index page to do navigation.

Note that the jekyll 4 upgrade isn't strictly tied to this PR and could be separated into another PR if desired. I don't think it's even required for the PR, but I haven't tried the other commit without it.

Screenshot 2024-03-19 at 1 04 45 PM

### CODE REVIEW

**Comment by tpendragon** [comment]
@hackartisan Presumably having both page and site-wide level ToC was too much?

**Comment by hackartisan** [comment]
@tpendragon I think it would be worth asking the team, especially new members. To me having the all the site contents there is a lot, even without page TOC above it. I'm also working off my recollections of our handbook discussion at last year's all hands.

**Comment by hackartisan** [comment]
If we want both though that's totally doable and I could add the site contents back in. There's also a world where you have the site contents and the page-level TOC is inline with that.

If we keep the site contents maybe we would want to organize them somehow

**Comment by tpendragon** [comment]
Maybe just the home page should have some links? I think the thing for me is that the bulleted list of links in the first page don't scream "navigation" to me. I may get used to it.

**Comment by hackartisan** [comment]
I've made some adjustments so the site index page titles are a little easier to parse, and now the page TOC shows in line with the site index in the sidebar:

Screenshot 2024-03-20 at 3 44 01 PM

@tpendragon what do you think of this?

**Review by tpendragon — APPROVED** [review]
I love it, good work!

**Pull request merged**
